### ISSUE TITLE
sysctl not found with an unprivileged user

### ISSUE THREAD

**Issue by HacKurx** [slimm609/checksec.sh#23]
Hi,

In Debian Jessie sysctl not found with an unprivileged user because /sbin/ is not present for a normal user's $PATHs.

Also remove the condition test for curl because he not integrated by default in some distributions. Use this only if Wget is not present.

Thanks, best regards

Here is the patch:
[patch.txt](https://github.com/slimm609/checksec.sh/files/82754/patch.txt)

**Comment by slimm609** [comment]
sysctl should not be in the path of an unpriv user, this script should be run as root, as root is required to modify most, if not all the parameters of that checksec is checking.      I can acutally remove both wget and curl from the checks because they are both checked during the update process itself.

**Comment by HacKurx** [comment]
It be useful to launch "checksec --proc-all" with an unprivileged user ;)

**Comment by HacKurx** [comment]
>  I can acutally remove both wget and curl from the checks because they are both checked during the update process itself.

Yes I have seen but just "curl" enough for Debian users :)

Thanks

**Comment by slimm609** [comment]
fixed
