### ISSUE TITLE
--file: non-zero exit code on missing hardening features

### ISSUE THREAD

**Issue by adrelanos** [slimm609/checksec.sh#38]
Could you add please non-zero exit codes when using `--file` if there are missing hardening features? That would be useful for using checksec inside automated test suites.

**Comment by slimm609** [comment]
i am not sure that I want to add that right now because not all use cases would have all features,   for example arm didn't support relro for a while,  if it doesn't support it, it shouldn't be an error.    You can use the --format json or xml which can easily be parsed by almost any testing suite out there.
