### ISSUE TITLE
Incorectly reported FORTIFY on PPC64 with binutils 2.29

### ISSUE THREAD

**Issue by voxik** [slimm609/checksec.sh#53]
I am using checksec to ensure that Ruby in Fedora is correctly fortified:

~~~
$ checksec -f libruby.so.2.4.1 | grep 'Full RELRO.*Canary found.*NX enabled.*DSO.*No RPATH.*No RUNPATH.*Yes.*\d*.*\d*.*libruby.so.2.4.1'
~~~

Unfortunately, with binutils 2.29 this check started to fail and this is the output:

~~~
$ checksec -f libruby.so.2.4.1
WARNING: 'openssl' not found! It's required for most checks.
WARNING: Not all necessary commands found. Some tests might not work!
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	FORTIFY	Fortified Fortifiable  FILE
Full RELRO      Canary found      NX enabled    DSO             No RPATH   No RUNPATH   No	0		0	libruby.so.2.4.1
~~~

Apparently, the "FORTIFY" used to be "Yes" on all platforms, while it is "No" for PPC64LE ATM.

And this is the analysis from the Fedora bug I opened [[1]]:

~~~
--- Comment 4 Nick Clifton 2017-08-08 17:29:43 CEST

Right, well I have found the cause, but not a solution.  The 2.29 linker for PowerPC is setting some extra symbol information, in order to help optimise run-time performance.  (This is related to BZ 14756316, but it is not exactly the same problem).

So, when libruby is built with the 2.28 linker the readelf command run by checksec would see output something like this:

  138: 0000000000000000  0 FUNC GLOBAL DEFAULT  UND __memmove_chk@GLIBC_2.17 (2)
 
But when it is built with the 2.29 linker the readelf output looks like this:

  257: 0000000000000000  0 FUNC GLOBAL DEFAULT [<localentry>: 8]   UND __memmove_chk@GLIBC_2.17 (2)
 
(This is true regardless of which version of readelf is used).

The problem is that checksec uses an awk script to extract the names of symbols, based upon the field in which they appear, and this field is hardcoded to be field number 8.  This works for the 2.28 linked libruby, but not the 2.29 libruby.  So the checksec script thinks that no *_chk functions are accessed by the library, and hence that it has not been fortified.

Now I do not think that the linker is wrong in adding this extra information.  In fact I think that it may be a requirement of the new ABI that IBM are creating.  So I would suggest that the real fix is to update checksec to cope with the new information.  Maybe by searching for a symbol name suffixed by an @ symbol for example, instead of replying upon field numbers.

I have not changed the component field of this BZ yet however as I want to see if there are any other suggestions.

Cheers
  Nick

--- Comment 5 Nick Clifton 2017-08-08 17:34:26 CEST

Addendum: It occurs to me that one thing I could do is to patch readelf so that this "extra" information is printed at the end of the line, rather than in the middle.  That way checksec's awk scanner would resume working.  Of course this might potentially break other tools that rely upon the latest format of the output...
~~~

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1479302

**Comment by slimm609** [comment]
do you know if the same is true for x86  binutils 2.28 vs 2.29?   I don't have any PPC arch to even begin to work on a fix if x86 doesn't have this issue

**Comment by voxik** [comment]
This was specifically PPC64LE (not even big endian PPC64). Other architectures supported by fedora were OK.

**Comment by slimm609** [comment]
hmm.   can you give me the full output of readelf -s libruby.so.2.4.1   on binutils 2.28 and 2.29?

**Comment by nickclifton** [comment]
The problem is specific to the PPC64LE in this particular case, but in theory it can affect any architecture.
All it takes is for an architecture's ABI to be enhanced to include extra information in an ELF symbol structure.  This extra information will appear in readelf's symbol description output, which will then confuse the AWK pattern matching rule in checksec.

**Comment by voxik** [comment]
Ping. Any progress by a chance?

**Comment by slimm609** [comment]
Nope.   The last status update, I asked for more information because I don't have a PPC64 arch machine to test on.

**Comment by slimm609** [comment]
I have asked for additional info multiple times with no response.   PPC64LE is not easily available to test so I am closing this issue

**Comment by voxik** [comment]
Just FYI, this \[[1]\] patch was applied to binutils in Fedora to fix the issue.

[1]: https://src.fedoraproject.org/rpms/binutils/c/b8265c46f7ddae23a792ee8306fbaaeacba83bf8?branch=master

**Comment by pedromfcarvalho** [comment]
Hello,

@slimm609 Would it be possible to re-open this issue?

Although there's a patch in Fedora to make the output of readelf work in this case for checksec, I think ideally it should work with an unpatched readelf for ppc64le libraries.

I'll provide some information below that can be useful for reproducing the issue.

Thanks a lot!!

Details:

I have attached the output of `readelf -h -W -s` on a recent ppc64le libruby.so, both using a patched Fedora readelf and a upstream readelf. The issue happens with the output of the unpatched upstream readelf. Note the presence of descriptors of `ST_OTHER` within the brackets for certain symbols.  With the Fedora patch, they appear at the end, so it doesn't affect the position of the symbol name field, but this is not the usual output. In the ouptut from the upstream readelf, `ST_OTHER` appears starting at the eigth field, and takes more than one field (I suspect the number of fields taken by the `ST_OTHER` descriptor is variable and can't be relied on).  Note also that the symbol name is not necessarily the last field, e.g. for some symbols with an undefined section index.

[readelf_output_fedora.txt](https://github.com/slimm609/checksec.sh/files/6804013/readelf_output_fedora.txt)
[readelf_output_upstream.txt](https://github.com/slimm609/checksec.sh/files/6804014/readelf_output_upstream.txt)

Besides that, it's possible to reproduce at least part of this issue on a x86-64 system, since readelf can be configured to be able to read ELFs from other target arches. I will describe how I did this.

I cloned binutils (which includes readelf) with:

```
git clone git://sourceware.org/git/binutils-gdb.git
```

The binutils README says you can use `--enable-targets=all` when configuring to enable binutils with all targets, but I think readelf itself might work regardless.

So a sample configuration would be, from within a separate build directory:

```
<path to root of binutils-gdb source>/configure --enable-targets=all --disable-gdb --disable-ld --disable-gold --disable-gas --disable-sim --disable-gprof
```

(there are some `--disable-*` for stuff we don't need, readelf will be compiled under this configuration)

Then `make` will compile.

Alternatively, if you're not in Fedora or Red Hat, the system readelf is likely unpatched and will produce the output that causes this issue.

After that, the ppc64le .so can be found at e.g.:

[https://koji.fedoraproject.org/koji/buildinfo?buildID=1756996](https://koji.fedoraproject.org/koji/buildinfo?buildID=1756996)

Or any more recent package build, scroll down for the ppc64le builds.  The `.so` is in the `ruby-libs` package. I tried attaching the `.so` directly for convenience but github doesn't allow it.

It can be extracted locally with something like:

```
rpm2cpio <path...>/ruby-libs-3.0.1-149.fc35.ppc64le.rpm | cpio -idmv
```

To make checksec use the readelf I built, I did something like:

```
readelf () { <path to binutils build directory>/binutils/readelf $@; }
export -f readelf # So that checksec will use the built readelf
```

Then I ran checkseck on the `.so` from the package I extracted, the .so should be in

```
<path to extracted ruby-devel package>/usr/lib64/libruby.so.<ver>
```

With the patched Fedora readelf, you get something like this, and won't see the issue:

```
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      Canary found      NX enabled    DSO             No RPATH   No RUNPATH   No Symbols	  Yes	8		25		usr/lib64/libruby.so.3.0.1
```

But with the upstream readelf, you get:

```
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      Canary found      NX enabled    DSO             No RPATH   No RUNPATH   No Symbols	  No	0		0		usr/lib64/libruby.so.3.0.1
```
