### ISSUE TITLE
Checksec apparmor

### ISSUE THREAD

**Issue by brokensh3ll** [slimm609/checksec.sh#61]
Hello,

Small idea to improve this script, as for selinux, apparmor should be part of the checksec -k

**Comment by slimm609** [comment]
I haven't used apparmor is a very long time and don't have any systems set up with apparmor,  I am happy to support PRs but I am not not familiar enough with apparmor to add it.

**Comment by nettrino** [comment]
@brokensh3ll what info would you like to see? Would the total profiles in enforce and complain mode as well as the no of processes in enforce or complain mode suffice?

**Comment by Maryse47** [comment]
Why not use `aa-status` instead? Why duplicate existing things?

**Comment by Maryse47** [comment]
The problem is that `checksec -k` is a way behind other existing tools like [kconfig-hardened-check](https://github.com/a13xp0p0v/kconfig-hardened-check), [lynis](https://github.com/CISOfy/lynis/), `aa-status`, etc. which makes it's usefulness very limited. I won't recommend any user to relying on it. Moreover making it at par with others will need to make existing code xx times bigger and barely maintainable (considering that checksec is just one file script). There won't be much value for users as this is only single command for single command trade.

Simply advising users to run `aa-status` (maybe also referring to other tools I mentioned) for more info in `checksec -k` output would be more honest approach.

**Comment by nettrino** [comment]
@Maryse47 adding/removing features is mainly up to the maintainer and secondarily to the community.
> the problem is that checksec -k is a way behind other existing tools like kconfig-hardened-check, lynis, aa-status, etc. which makes it's usefulness very limited. I won't recommend any user to relying on it. 

Many pieces of software are behind then get attention and worked on. The question is, is this a legacy-only project or an ongoing one.

**Comment by Maryse47** [comment]
This is a matter of priorities. `checksec` is a great tool to examine security of binaries. The old Unix philosophy is "Write programs that do one thing and do it well."

**Comment by slimm609** [comment]
It's not legacy only but I don't currently have time to setup, learn, and update the code to run against apparmor.    I haven't touched apparmor in over a decade.

**Comment by nettrino** [comment]
@slimm609 that's fine - I simply asked what info would be useful and if you are taking PRs. A simple start would be to display profiles and processes in complain/enforce mode.

**Comment by codytubbs** [comment]
@nettrino seems easy enough to create an --aa (-a) option that calls `aa-status` if exists. \**shrug\**
